const FIELD_TYPES = {
    STRING: 'STRING',
    TEXTAREA: 'TEXTAREA',
    NUMBER: 'NUMBER',
    DATE: 'DATE',
    GUID: 'GUID',
    BOOLEAN: 'BOOLEAN',
    BOOLEAN_YESNO: 'BOOLEAN_YESNO'
};

export default FIELD_TYPES;