//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDApplication { get; set; }
        public int IDActionType { get; set; }
        public Nullable<int> IDCustomActionType { get; set; }
        public string UserName { get; set; }
        public System.DateTime Recorded { get; set; }
        public string Data { get; set; }
        public string Reference { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
