//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Octacom_OICS_Entities : DbContext
    {
        public Octacom_OICS_Entities()
            : base("name=Octacom_OICS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OICSConnectorActivity> OICSConnectorActivities { get; set; }
        public virtual DbSet<OICSConnectorProcess> OICSConnectorProcesses { get; set; }
        public virtual DbSet<AribaProcessedException> AribaProcessedExceptions { get; set; }
    
        public virtual ObjectResult<GetAribaExceptionBatchType_Result> GetAribaExceptionBatchType(string primaryFileName)
        {
            var primaryFileNameParameter = primaryFileName != null ?
                new ObjectParameter("primaryFileName", primaryFileName) :
                new ObjectParameter("primaryFileName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAribaExceptionBatchType_Result>("GetAribaExceptionBatchType", primaryFileNameParameter);
        }
    
        public virtual ObjectResult<GetAribaExceptionSender_Result> GetAribaExceptionSender(string primaryFileName)
        {
            var primaryFileNameParameter = primaryFileName != null ?
                new ObjectParameter("primaryFileName", primaryFileName) :
                new ObjectParameter("primaryFileName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAribaExceptionSender_Result>("GetAribaExceptionSender", primaryFileNameParameter);
        }
    
        public virtual ObjectResult<GetAribaWaitingExceptionList_Result> GetAribaWaitingExceptionList(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAribaWaitingExceptionList_Result>("GetAribaWaitingExceptionList", startDateParameter, endDateParameter);
        }
    }
}
