//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Odiss_OPG_BaseEntities : DbContext
    {
        public Odiss_OPG_BaseEntities()
            : base("name=Odiss_OPG_BaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<Databas> Databases { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<tblDirectory> tblDirectories { get; set; }
        public virtual DbSet<tblException> tblExceptions { get; set; }
        public virtual DbSet<tblGroup> tblGroups { get; set; }
        public virtual DbSet<tblGroupLine> tblGroupLines { get; set; }
        public virtual DbSet<tblLocation> tblLocations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersDocument> UsersDocuments { get; set; }
        public virtual DbSet<UsersGroup> UsersGroups { get; set; }
    }
}
