//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDApplication { get; set; }
        public string Name { get; set; }
        public byte Type { get; set; }
        public bool Active { get; set; }
        public string DataSource { get; set; }
        public string FileNamePrefix { get; set; }
        public Nullable<byte> GraphicalType { get; set; }
        public string GraphicalOptions { get; set; }
        public Nullable<int> ResultOrder { get; set; }
        public string Options { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
