//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OPG_LOG
    {
        public int ID { get; set; }
        public System.DateTime PROCESS_DATE { get; set; }
        public string BATCH_ID { get; set; }
        public string BATCH_TYPE { get; set; }
        public string XML_FILENAME { get; set; }
        public string PDF_FILENAME { get; set; }
        public string PDF_FILENAME_NEW { get; set; }
        public string DOC_TYPE { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VENDOR_ID { get; set; }
        public string PO_NUMBER { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string SAP_PO_NUMBER { get; set; }
        public string UTILITY_ACCT_NUMBER { get; set; }
        public decimal TOTAL_AMOUNT { get; set; }
        public bool IS_EXCEPTION { get; set; }
        public string EXCEPTION_CODE { get; set; }
        public string RTV_REJECT_TYPE { get; set; }
        public string RTV_REJECT_FILE { get; set; }
        public bool RTV_REPORT_DONE { get; set; }
        public string SourceImage { get; set; }
    }
}
