//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBatchTrack
    {
        public System.Guid BID { get; set; }
        public string TicketNo { get; set; }
        public string BatchID { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public Nullable<long> InvoiceCount { get; set; }
        public Nullable<long> EnvelopeCount { get; set; }
        public Nullable<long> RTCCount { get; set; }
        public Nullable<long> RTVCount { get; set; }
        public Nullable<long> PageCount { get; set; }
        public string Stage { get; set; }
        public string BatchType { get; set; }
        public string CreationOP { get; set; }
        public Nullable<System.DateTime> TicketDate { get; set; }
        public Nullable<long> PrepInvoiceCount { get; set; }
    }
}
