//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGroup()
        {
            this.tblGroupLines = new HashSet<tblGroupLine>();
        }
    
        public System.Guid GUID { get; set; }
        public string DirectoryID { get; set; }
        public string DocType { get; set; }
        public string Filename { get; set; }
        public string Source { get; set; }
        public string Sender { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string OriginalFilename { get; set; }
        public string XMLFile { get; set; }
        public string OctProcessFilename { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
        public string InvoiceNo { get; set; }
        public string PONumber { get; set; }
        public string Utility { get; set; }
        public string ReferenceNo { get; set; }
        public string ExceptionCode { get; set; }
        public string AribaExceptionCode { get; set; }
        public string AribaExceptionReason { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> I_CaptureDate { get; set; }
        public Nullable<int> Archived { get; set; }
        public string SourceImage { get; set; }
        public string ArchiveComment { get; set; }
        public Nullable<System.DateTime> ArchivedDate { get; set; }
        public string Status { get; set; }

        [JsonIgnore]
        public virtual tblDirectory tblDirectory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<tblGroupLine> tblGroupLines { get; set; }
        public virtual ICollection<tblGroupLine> lineItems { get; set; }        
    }
}
