//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Email
    {
        public Nullable<System.DateTime> RecievedDate { get; set; }
        public string Sender { get; set; }
        public string MailBody { get; set; }
        public Nullable<int> NoAttachments { get; set; }
        public Nullable<long> TicketNo { get; set; }
        public bool Exception { get; set; }
        public string ExceptionType { get; set; }
        public bool Returned { get; set; }
        public string Subject { get; set; }
        public string UID { get; set; }
        public string FileName { get; set; }
        public string FileLocation { get; set; }
        public string ExceptionReason { get; set; }
        public Nullable<bool> AttachmentException { get; set; }
        public string ConvertedFileLocation { get; set; }
        public Nullable<bool> isGood { get; set; }
        public Nullable<System.DateTime> ConvertTime { get; set; }
        public System.Guid EID { get; set; }
        public string ProcessFileName { get; set; }
        public string FileExtension { get; set; }
        public string AttachExpCode { get; set; }
        public Nullable<bool> RTV { get; set; }
        public string EmailBackupFile { get; set; }
        public bool PartialException { get; set; }
        public string ExceptionDetails { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public string EmailAddress { get; set; }
        public string SvcProcessedFileName { get; set; }
        public string SvcExceptionReason { get; set; }
        public Nullable<bool> SvcException { get; set; }
        public string SvcFileExtension { get; set; }
    }
}
