//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Audits = new HashSet<Audit>();
            this.Fields = new HashSet<Field>();
            this.Reports = new HashSet<Report>();
            this.UsersDocuments = new HashSet<UsersDocument>();
            this.Users = new HashSet<User>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid IDDatabase { get; set; }
        public Nullable<System.Guid> IDFieldGroupBy { get; set; }
        public string Name { get; set; }
        public string SearchTitle { get; set; }
        public string SortBy { get; set; }
        public Nullable<bool> RestrictDocumentAccess { get; set; }
        public Nullable<int> TabOrder { get; set; }
        public string DocumentsPath { get; set; }
        public bool EnablePages { get; set; }
        public bool EnableProperties { get; set; }
        public bool EnableEditProperties { get; set; }
        public bool EnableNotes { get; set; }
        public bool EnableEmail { get; set; }
        public bool EnableSubmitDocuments { get; set; }
        public bool EnableReports { get; set; }
        public Nullable<byte> Type { get; set; }
        public string CustomData { get; set; }
        public string TableName { get; set; }
        public Nullable<bool> EnableCreate { get; set; }
        public Nullable<bool> EnableUpdate { get; set; }
        public Nullable<bool> EnableDelete { get; set; }
        public Nullable<bool> EnableItemlinesCreate { get; set; }
        public Nullable<bool> EnableItemlinesUpdate { get; set; }
        public Nullable<bool> EnableItemlinesDelete { get; set; }
    
        public virtual Databas Databas { get; set; }
        public virtual Field Field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit> Audits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Field> Fields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersDocument> UsersDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
