//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AribaProcessedException
    {
        public int OICSConnectorProcessId { get; set; }
        public Nullable<int> ServiceState { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string ServiceDetails { get; set; }
    }
}
