//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Field()
        {
            this.Applications = new HashSet<Application>();
            this.UsersDocuments = new HashSet<UsersDocument>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid IDApplication { get; set; }
        public string Name { get; set; }
        public byte Type { get; set; }
        public string MapTo { get; set; }
        public bool Editable { get; set; }
        public Nullable<int> FilterOrder { get; set; }
        public Nullable<int> ResultOrder { get; set; }
        public Nullable<byte> FilterType { get; set; }
        public string FilterCommand { get; set; }
        public string FilterData { get; set; }
        public Nullable<bool> EnableRestriction { get; set; }
        public string HeaderGroupName { get; set; }
        public Nullable<bool> EnableAutoComplete { get; set; }
        public Nullable<byte> AutoComplete_FilterType { get; set; }
        public string AutoComplete_FilterCommand { get; set; }
        public string AutoComplete_MapFields { get; set; }
        public string Format { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<byte> VisibilityType { get; set; }
        public string ShowInView { get; set; }
        public string Options { get; set; }
        public Nullable<bool> NotVisibleList { get; set; }
        public Nullable<bool> NotVisibleViewer { get; set; }
        public Nullable<bool> NotVisibleSubmit { get; set; }
        public Nullable<bool> NotVisibleFilter { get; set; }
        public Nullable<bool> MaxLen { get; set; }
        public Nullable<bool> NotVisibleExport { get; set; }
        public Nullable<bool> IsKey { get; set; }
        public string ValidationRulesJson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersDocument> UsersDocuments { get; set; }
    }
}
