//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public System.Guid ID { get; set; }
        public System.Guid IDDocument { get; set; }
        public System.DateTime Created { get; set; }
        public string Author { get; set; }
        public string Note1 { get; set; }
    }
}
