//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OICSConnectorActivity
    {
        public int OICSConnectorActivityId { get; set; }
        public string ProcessingStage { get; set; }
        public byte MessageLevel { get; set; }
        public string MessageCode { get; set; }
        public string Data { get; set; }
        public System.DateTime ActivityTime { get; set; }
        public int OICSConnectorProcessId { get; set; }
        public byte DataType { get; set; }
        public string MessageText { get; set; }
    
        public virtual OICSConnectorProcess OICSConnectorProcess { get; set; }
    }
}
