//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRTVReturn
    {
        public System.Guid RID { get; set; }
        public string TicketNo { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string VendorNo { get; set; }
        public string JobName { get; set; }
        public Nullable<decimal> Postage { get; set; }
        public string CreatorOP { get; set; }
        public string ExceptionType { get; set; }
        public string VendorName { get; set; }
        public string Source { get; set; }
        public string PO { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> TicketDate { get; set; }
        public Nullable<long> SeqNum { get; set; }
        public Nullable<long> NoPages { get; set; }
    }
}
