//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREJECT_LIST_PO_LEGACY
    {
        public string PO_NUMBER { get; set; }
        public string REJECT_EMAIL { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FileImportName { get; set; }
    }
}
