//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorProcess
    {
        public System.Guid Guid { get; set; }
        public string PrivateID { get; set; }
        public string Name { get; set; }
        public string InvoiceType { get; set; }
        public string V_EXT_DESC { get; set; }
        public string V_INT_DESC { get; set; }
        public System.DateTime MODIFY_DATE { get; set; }
        public string MODIFY_TYPE { get; set; }
    }
}
