//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Sessions = new HashSet<Session>();
            this.UsersDocuments = new HashSet<UsersDocument>();
            this.Applications = new HashSet<Application>();
        }
    
        public System.Guid ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public byte Type { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneOffice { get; set; }
        public string PhoneMobile { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> Expire { get; set; }
        public Nullable<long> Permissions { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LockAccessUntil { get; set; }
        public Nullable<int> WrongAccessAttempts { get; set; }
        public Nullable<bool> ChangePassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersDocument> UsersDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
    }
}
