//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.Odiss.OPG.Lib.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDocument
    {
        public System.Guid ID { get; set; }
        public System.Guid IDUser { get; set; }
        public System.Guid IDApplication { get; set; }
        public Nullable<System.Guid> IDField { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Field Field { get; set; }
        public virtual User User { get; set; }
    }
}
