//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octacom.OPG.UnitTest.OctacomService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OctacomService.InvoiceServiceSoap")]
    public interface InvoiceServiceSoap {
        
        // CODEGEN: Generating message contract since element name xmlFullFileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendInvoice", ReplyAction="*")]
        Octacom.OPG.UnitTest.OctacomService.SendInvoiceResponse SendInvoice(Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<Octacom.OPG.UnitTest.OctacomService.SendInvoiceResponse> SendInvoiceAsync(Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendInvoice", Namespace="http://tempuri.org/", Order=0)]
        public Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequestBody Body;
        
        public SendInvoiceRequest() {
        }
        
        public SendInvoiceRequest(Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendInvoiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime processDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlFullFileName;
        
        public SendInvoiceRequestBody() {
        }
        
        public SendInvoiceRequestBody(System.DateTime processDate, string xmlFullFileName) {
            this.processDate = processDate;
            this.xmlFullFileName = xmlFullFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendInvoiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Octacom.OPG.UnitTest.OctacomService.SendInvoiceResponseBody Body;
        
        public SendInvoiceResponse() {
        }
        
        public SendInvoiceResponse(Octacom.OPG.UnitTest.OctacomService.SendInvoiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendInvoiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendInvoiceResult;
        
        public SendInvoiceResponseBody() {
        }
        
        public SendInvoiceResponseBody(string SendInvoiceResult) {
            this.SendInvoiceResult = SendInvoiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvoiceServiceSoapChannel : Octacom.OPG.UnitTest.OctacomService.InvoiceServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvoiceServiceSoapClient : System.ServiceModel.ClientBase<Octacom.OPG.UnitTest.OctacomService.InvoiceServiceSoap>, Octacom.OPG.UnitTest.OctacomService.InvoiceServiceSoap {
        
        public InvoiceServiceSoapClient() {
        }
        
        public InvoiceServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvoiceServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Octacom.OPG.UnitTest.OctacomService.SendInvoiceResponse Octacom.OPG.UnitTest.OctacomService.InvoiceServiceSoap.SendInvoice(Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequest request) {
            return base.Channel.SendInvoice(request);
        }
        
        public string SendInvoice(System.DateTime processDate, string xmlFullFileName) {
            Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequest inValue = new Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequest();
            inValue.Body = new Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequestBody();
            inValue.Body.processDate = processDate;
            inValue.Body.xmlFullFileName = xmlFullFileName;
            Octacom.OPG.UnitTest.OctacomService.SendInvoiceResponse retVal = ((Octacom.OPG.UnitTest.OctacomService.InvoiceServiceSoap)(this)).SendInvoice(inValue);
            return retVal.Body.SendInvoiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Octacom.OPG.UnitTest.OctacomService.SendInvoiceResponse> Octacom.OPG.UnitTest.OctacomService.InvoiceServiceSoap.SendInvoiceAsync(Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequest request) {
            return base.Channel.SendInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Octacom.OPG.UnitTest.OctacomService.SendInvoiceResponse> SendInvoiceAsync(System.DateTime processDate, string xmlFullFileName) {
            Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequest inValue = new Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequest();
            inValue.Body = new Octacom.OPG.UnitTest.OctacomService.SendInvoiceRequestBody();
            inValue.Body.processDate = processDate;
            inValue.Body.xmlFullFileName = xmlFullFileName;
            return ((Octacom.OPG.UnitTest.OctacomService.InvoiceServiceSoap)(this)).SendInvoiceAsync(inValue);
        }
    }
}
